"""add column entity

Revision ID: 3531ce3277fa
Revises: 345cde618261
Create Date: 2025-05-15 22:50:45.478942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3531ce3277fa'
down_revision: Union[str, None] = '345cde618261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('ogrn', sa.String(), nullable=True),
    sa.Column('kpp', sa.String(), nullable=True),
    sa.Column('payload', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity')
    # ### end Alembic commands ###
