"""t

Revision ID: 8e4c5b70b780
Revises: 6e2e127aeffc
Create Date: 2025-06-15 14:27:05.174058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4c5b70b780'
down_revision: Union[str, None] = '6e2e127aeffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrants',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('unique_code_profile', sa.String(), nullable=False),
    sa.Column('snils', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrants')
    # ### end Alembic commands ###
