"""rrr

Revision ID: a2be111206b5
Revises: 8e4c5b70b780
Create Date: 2025-06-21 15:57:51.816477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2be111206b5'
down_revision: Union[str, None] = '8e4c5b70b780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_epgu', sa.Integer(), nullable=True),
    sa.Column('id_entrant', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('actual', sa.Boolean(), nullable=True),
    sa.Column('id_education_level_group', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    # ### end Alembic commands ###
