"""add column 

Revision ID: d8c5c76dbf90
Revises: 6213ec911431
Create Date: 2025-05-19 07:55:34.304677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c5c76dbf90'
down_revision: Union[str, None] = '6213ec911431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity', 'payload')
    op.drop_column('entity', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entity', sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
