"""add column file_type

Revision ID: e945531033d5
Revises: dfea4d39062e
Create Date: 2025-06-14 09:42:55.308126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e945531033d5'
down_revision: Union[str, None] = 'dfea4d39062e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Direction_cls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('actual', sa.Boolean(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('education_level_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Direction_cls')
    # ### end Alembic commands ###
