"""add colu filype

Revision ID: ed53bd639ad1
Revises: c33a531267b4
Create Date: 2025-06-14 10:57:08.231726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed53bd639ad1'
down_revision: Union[str, None] = 'c33a531267b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Direction_cls', sa.Column('Id_Direction', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Direction_cls', 'Id_Direction')
    # ### end Alembic commands ###
